### PR TITLE
Add chime icon handle and timezone config option

### PR DESCRIPTION
**Pull request by goldhand**
This adds a aws chime icon when that is in the meeting url.

today-tomorrow-demo

It also adds a config for time_zone, so if the system isn't working (mine wasn't) users can manually specify a time zone.

I also changed:

```
if online_meeting == u'true' and body_html:
    # handle online meeting url
```

to

```
if body_html:
    # handle online meeting url
```

Because that `event.is_online_meeting` was returning false for me when all I have are online meetings now days lol.
Not sure what that prevented anyway.

*Note: I changed some other things (eg tconf instead of tc but that's not in PR, also blocked out my server uri in screenshot*

Screen Shot 2021-07-28 at 4 20 00 AM

This also fixes the regex example in readme.

### CODE REVIEW

**Comment by jeeftor** [comment]
Can you update the MR and I'll pull it in.  

I no longer use this plugin but happy to release a new version for those that do.

**Comment by goldhand** [comment]
Just fixed it! Yeah it's awesome actually, I love it

**Comment by jeeftor** [comment]
Just merged this in - I'll try to get a new release pushed up to GitHub -> however as I no longer use the repo if you wanted I could transfer it over to you?

**Comment by jeeftor** [comment]
and/or make you a collaborator

**Pull request merged**
